In [1]:
## Problem 2

In [12]:
import numpy as np

In [13]:
pb = 0.1
pe = 0.2
pa = np.array([0.9, 0.8, 0.3, 0.1])
pj = np.array([0.9, 0.2])
pm = np.array([0.7, 0.1])

In [14]:
### Earthquake did not happen

In [15]:
num = pb * (1 - pe) * (pa[1] * pj[0] * pm[0] + (1 - pa[1]) * pj[1] * pm[1])

num

0.04064000000000001

In [16]:
nnum = (1 - pb) * (1 - pe) * (pa[3] * pj[0] * pm[0] + (1 - pa[3]) * pj[1] * pm[1])

nnum

0.05832000000000001

In [17]:
num / (num + nnum)

0.4106709781729992

In [18]:
### Earthquake did happen

In [19]:
num = pb * pe * (pa[0] * pj[0] * pm[0] + (1 - pa[0]) * pj[1] * pm[1])

num

0.011380000000000001

In [20]:
nnum = (1 - pb) * pe * (pa[2] * pj[0] * pm[0] + (1 - pa[2]) * pj[1] * pm[1])

nnum

0.03654000000000001

In [21]:
num / (num + nnum)

0.23747913188647743

In [ ]:
## Problem 3

In [23]:
import numpy as np

In [22]:
p = np.array([[[36, 4], [2, 8]], [[9, 1], [8, 32]]])

# Normalize into probabilities
p = p/p.sum()

p

array([[[0.36, 0.04],
        [0.02, 0.08]],

       [[0.09, 0.01],
        [0.08, 0.32]]])

In [40]:
def info(i0, i1):
    i2 = 3 - i0 - i1
    p01 = p.sum(axis=i2)
    p0 = p01.sum(axis=0)
    p1 = p01.sum(axis=1)
    pprod = (np.expand_dims(p0, axis=1) @ np.expand_dims(p1, axis=0)).T
    return np.sum(p01 * (np.log2(p01) - np.log2(pprod)))

In [41]:
info(0, 1), info(0, 2), info(1, 2)

(0.2780719051126377, 0.1328449618090321, 0.3973126097494868)

Maximum Spanning Tree: X -> Y -> Z

In [39]:
p01 = p.sum(axis=1)
p0 = p01.sum(axis=0)
p1 = p01.sum(axis=1)
pprod = (np.expand_dims(p0, axis=1) @ np.expand_dims(p1, axis=0)).T

p01, p0, p1, pprod, np.sum(p01 * (np.log2(p01) - np.log2(pprod)))

(array([[0.38, 0.12],
        [0.17, 0.33]]),
 array([0.55, 0.45]),
 array([0.5, 0.5]),
 array([[0.275, 0.225],
        [0.275, 0.225]]),
 0.1328449618090321)